common:
    resource: "@CommonBundle/Resources/config/routing.yml"
    prefix:   /

event:
    type: rest
    resource: "@EventBundle/Controller/EventController.php"

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
