# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    event.form.requirement_type:
        class: EventBundle\Form\RequirementType
        arguments: ["@event.form.item_transformer"]
        tags:
            - { name: form.type }

    event.form.item_transformer:
        class: EventBundle\Form\ItemTransformer
        arguments: ["@doctrine.orm.entity_manager"]

    event.file_uploader:
        class: AppBundle\Utils\FileUploader
        arguments: ['%documents_directory%']

    event.document_upload_listener:
        class: AppBundle\Listener\DocumentUploadListener
        arguments: ['@event.file_uploader']
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }