services:
    common_bundle.notification_listener:
        class: CommonBundle\EventListener\MyNotificationListListener
        tags:
            - { name: kernel.event_listener, event: theme.notifications, method: onListNotifications }
            
    common_bundle.message_list_listener:
        class: CommonBundle\EventListener\MyMessageListListener
        tags:
            - { name: kernel.event_listener, event: theme.messages, method: onListMessages }
            
    common_bundle.menu_listener:
        class: CommonBundle\EventListener\MyMenuItemListListener
        tags:
            - { name: kernel.event_listener, event: theme.sidebar_setup_menu, method: onSetupMenu }
            
    common_bundle.breadcrumb_listener:
        class: CommonBundle\EventListener\MyMenuItemListListener
        tags:
            - { name: kernel.event_listener, event:theme.breadcrumb, method:onSetupMenu }
            
parameters:
    common_bundle.notification_listener.class: CommonBundle\EventListener\MyNotificationListListener
    common_bundle.show_user_listener.class: CommonBundle\EventListener\MyMessageListListener
    common_bundle.menu_listener.class: CommonBundle\EventListener\MyMenuItemListListener

        