<?php

namespace UserBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    /**
     * @param $apiKey
     * @return array
     */
    public function findByApiKey($apiKey)
    {
        $queryBuilder = $this->createQueryBuilder('u');
        $queryBuilder->andWhere('u.apiKey = :apiKey');
        $queryBuilder->setParameter('apiKey', $apiKey);

        return $queryBuilder->getQuery()->getResult();
    }
}
