<?php

namespace EventBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends EntityRepository
{
    public function findLikeName($name) {
        $queryBuilder = $this->createQueryBuilder('i')
            ->andWhere('i.name like :name')
            ->setParameter('name', "%$name%");

        return $queryBuilder->getQuery()->getResult();
    }
}
