<?php

namespace EventBundle\Repository;
use Doctrine\ORM\EntityRepository;
use EventBundle\Entity\Event;
use UserBundle\Entity\User;

/**
 * ParticipationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipationRepository extends EntityRepository
{
    /**
     * @param Event $event
     * @return array
     */
    public function findByEvent(Event $event)
    {
        $queryBuilder = $this->createQueryBuilder('p');
        $queryBuilder->innerJoin('p.event', 'e');
        $queryBuilder->andWhere('e.id = eventId');
        $queryBuilder->setParameter('eventId', $event->getId());

        return $queryBuilder->getQuery()->getResult();
    }

    /**
     * @param User $user
     * @return array
     */
    public function findByUser(User $user)
    {
        $queryBuilder = $this->createQueryBuilder('p');
        $queryBuilder->innerJoin('p.user', 'u');
        $queryBuilder->andWhere('u.id = userId');
        $queryBuilder->setParameter('userId', $user->getId());

        return $queryBuilder->getQuery()->getResult();
    }
}
