<?php

namespace EventBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProvisionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProvisionsRepository extends EntityRepository
{
}
