<?php

namespace EventBundle\Repository;

/**
 * RequirementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequirementRepository extends \Doctrine\ORM\EntityRepository
{
}
