event_create:
    path:     /event/create
    defaults: { _controller: EventBundle:Event:create }

event_list:
    path:     /events/{user_id}
    defaults: { _controller: EventBundle:Event:list }
    requirements:
        user_id: \d

event_view:
    path:     /event/{id}
    defaults: { _controller: EventBundle:Event:view }
    requirements:
        id: \d

event_update:
    path:     /event/update/{id}
    defaults: { _controller: EventBundle:Event:update }
    requirements:
        id: \d
event_remove:
    path:     /event/remove/{id}
    defaults: { _controller: EventBundle:Event:remove }
    requirements:
        id: \d
