event_event:
    type: rest
    resource: "@EventBundle/Controller/EventController.php"

event_requirement:
    type: rest
    resource: "@EventBundle/Controller/RequirementController.php"

autocomplete_item:
    path:     /event/autocomp_requirement
    defaults: { _controller: EventBundle:Event:autocomplete }
    options:
        expose: true
