event_event:
    type: rest
    resource: "@EventBundle/Controller/EventController.php"

event_requirement:
    type: rest
    resource: "@EventBundle/Controller/RequirementController.php"

event_item:
    type: rest
    resource: "@EventBundle/Controller/ItemController.php"

event_participation:
    type: rest
    resource: "@EventBundle/Controller/ParticipationController.php"

event_provision:
    type: rest
    resource: "@EventBundle/Controller/ProvisionController.php"

autocomplete_item:
    path:     /event/autocomp_requirement
    defaults: { _controller: EventBundle:Event:autocomplete }
    options:
        expose: true
