event_create:
    path:     /event/create
    defaults: { _controller: EventBundle:Event:create }

event_list:
    path:     /events
    defaults: { _controller: EventBundle:Event:list }
    requirements:
        user_id: \d

event_view:
    path:     /event/{event_id}
    defaults: { _controller: EventBundle:Event:view }
    requirements:
        event_id: \d

event_update:
    path:     /event/update/{event_id}
    defaults: { _controller: EventBundle:Event:update }
    requirements:
        event_id: \d
event_remove:
    path:     /event/remove/{event_id}
    defaults: { _controller: EventBundle:Event:remove }
    requirements:
        event_id: \d
        
event_addrequirement:
    path:     /event/add_requirement/{event_id}
    defaults: { _controller: EventBundle:Event:addRequirementEvent }
    requirements:
        event_id: \d
        
event_addparticipations:
    path:     /event/add_participations/{event_id}
    defaults: { _controller: EventBundle:Participation:addParticipationsEvent }
    requirements:
        event_id: \d
        
book_sleep:
    path:     /event/book_sleep/{participation_id}
    defaults: { _controller: EventBundle:Participation:bookingSleep }
    requirements:
        participation_id: \d
        
        
event_removerequirement:
    path:     /event/remove_requirement/{requirement_id}
    defaults: { _controller: EventBundle:Event:removeRequirementEvent }
    requirements:
        requirement_id: \d
        
autocomplete_item:
    path:     /event/autocomp_requirement
    defaults: { _controller: EventBundle:Event:autocomplete }
    options:
        expose: true
    
add_provision:
    path:     /event/add_provision/{event_id}/{requirement_id}
    defaults: { _controller: EventBundle:Provisions:addProvision }
    requirements:
        requirement_id: \d
        event_id: \d
        
participation_response:
    path:     /event/response/{participation_id}
    defaults: { _controller: EventBundle:Participation:response }
    requirements:
        participation_id: \d

    
